[package]
name = "tracing-opentelemetry"
version = "0.1.0"
authors = ["Julian Tescher <julian@tescher.me>"]
edition = "2018"

[dependencies]
opentelemetry = { git = "https://github.com/jtescher/opentelemetry-rust" }
rand = "0.7.2"
tracing-core = "0.1.7"
tracing-subscriber = "0.2.0-alpha.1"

[dev-dependencies]
tracing = "0.1.10"
tracing-attributes = "0.1.5"
